// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source ./service.go -destination ./mocks/lsp_mock.go
//

// Package mock_lsp is a generated GoMock package.
package mock_lsp

import (
	context "context"
	reflect "reflect"

	lsp "github.com/opencode-ai/opencode/internal/lsp"
	gomock "go.uber.org/mock/gomock"
)

// MockLspService is a mock of LspService interface.
type MockLspService struct {
	ctrl     *gomock.Controller
	recorder *MockLspServiceMockRecorder
	isgomock struct{}
}

// MockLspServiceMockRecorder is the mock recorder for MockLspService.
type MockLspServiceMockRecorder struct {
	mock *MockLspService
}

// NewMockLspService creates a new mock instance.
func NewMockLspService(ctrl *gomock.Controller) *MockLspService {
	mock := &MockLspService{ctrl: ctrl}
	mock.recorder = &MockLspServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLspService) EXPECT() *MockLspServiceMockRecorder {
	return m.recorder
}

// Clients mocks base method.
func (m *MockLspService) Clients() map[string]*lsp.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clients")
	ret0, _ := ret[0].(map[string]*lsp.Client)
	return ret0
}

// Clients indicates an expected call of Clients.
func (mr *MockLspServiceMockRecorder) Clients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clients", reflect.TypeOf((*MockLspService)(nil).Clients))
}

// ClientsCh mocks base method.
func (m *MockLspService) ClientsCh() <-chan *lsp.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientsCh")
	ret0, _ := ret[0].(<-chan *lsp.Client)
	return ret0
}

// ClientsCh indicates an expected call of ClientsCh.
func (mr *MockLspServiceMockRecorder) ClientsCh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientsCh", reflect.TypeOf((*MockLspService)(nil).ClientsCh))
}

// ClientsForFile mocks base method.
func (m *MockLspService) ClientsForFile(filePath string) []*lsp.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientsForFile", filePath)
	ret0, _ := ret[0].([]*lsp.Client)
	return ret0
}

// ClientsForFile indicates an expected call of ClientsForFile.
func (mr *MockLspServiceMockRecorder) ClientsForFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientsForFile", reflect.TypeOf((*MockLspService)(nil).ClientsForFile), filePath)
}

// ForceShutdown mocks base method.
func (m *MockLspService) ForceShutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForceShutdown")
}

// ForceShutdown indicates an expected call of ForceShutdown.
func (mr *MockLspServiceMockRecorder) ForceShutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceShutdown", reflect.TypeOf((*MockLspService)(nil).ForceShutdown))
}

// FormatDiagnostics mocks base method.
func (m *MockLspService) FormatDiagnostics(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatDiagnostics", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatDiagnostics indicates an expected call of FormatDiagnostics.
func (mr *MockLspServiceMockRecorder) FormatDiagnostics(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatDiagnostics", reflect.TypeOf((*MockLspService)(nil).FormatDiagnostics), filePath)
}

// Init mocks base method.
func (m *MockLspService) Init(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init", ctx)
}

// Init indicates an expected call of Init.
func (mr *MockLspServiceMockRecorder) Init(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockLspService)(nil).Init), ctx)
}

// NotifyOpenFile mocks base method.
func (m *MockLspService) NotifyOpenFile(ctx context.Context, filePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyOpenFile", ctx, filePath)
}

// NotifyOpenFile indicates an expected call of NotifyOpenFile.
func (mr *MockLspServiceMockRecorder) NotifyOpenFile(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyOpenFile", reflect.TypeOf((*MockLspService)(nil).NotifyOpenFile), ctx, filePath)
}

// Shutdown mocks base method.
func (m *MockLspService) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockLspServiceMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockLspService)(nil).Shutdown), ctx)
}

// WaitForDiagnostics mocks base method.
func (m *MockLspService) WaitForDiagnostics(ctx context.Context, filePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitForDiagnostics", ctx, filePath)
}

// WaitForDiagnostics indicates an expected call of WaitForDiagnostics.
func (mr *MockLspServiceMockRecorder) WaitForDiagnostics(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDiagnostics", reflect.TypeOf((*MockLspService)(nil).WaitForDiagnostics), ctx, filePath)
}
