package models

const (
	ProviderAnthropic ModelProvider = "anthropic"

	// Models
	Claude45Opus   ModelID = "claude-4.5-opus"
	Claude46Opus   ModelID = "claude-4.6-opus"
	Claude47Opus   ModelID = "claude-4.7-opus"
	Claude48Opus   ModelID = "claude-4.8-opus"
	Claude5Opus    ModelID = "claude-5-opus"
	Claude55Opus   ModelID = "claude-5.5-opus"
	Claude46Sonnet ModelID = "claude-4.6-sonnet"
	Claude5Sonnet  ModelID = "claude-5-sonnet"
	Claude55Sonnet ModelID = "claude-5.5-sonnet"
	Claude45Haiku  ModelID = "claude-4.5-haiku"
	Claude55Haiku  ModelID = "claude-5.5-haiku"
	ClaudeFable5   ModelID = "claude-fable-5"
	ClaudeFable51  ModelID = "claude-fable-5-1"
)

// https://docs.anthropic.com/en/docs/about-claude/models/all-models
var AnthropicModels = map[ModelID]Model{
	Claude45Opus: {
		ID:                  Claude45Opus,
		Name:                "Claude 4.5 Opus",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-opus-4-5-20251101",
		CostPer1MIn:         5.0,
		CostPer1MInCached:   6.75,
		CostPer1MOutCached:  0.50,
		CostPer1MOut:        25.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    32000,
		CanReason:           true,
		SupportsToolSearch:  true,
		SupportsAttachments: true,
	},
	Claude46Opus: {
		ID:                       Claude46Opus,
		Name:                     "Claude 4.6 Opus",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-opus-4-6",
		CostPer1MIn:              5.0,
		CostPer1MInCached:        6.25,
		CostPer1MOutCached:       0.50,
		CostPer1MOut:             25.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude47Opus: {
		ID:                       Claude47Opus,
		Name:                     "Claude 4.7 Opus",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-opus-4-7",
		CostPer1MIn:              5.0,
		CostPer1MInCached:        6.25,
		CostPer1MOutCached:       0.50,
		CostPer1MOut:             25.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude48Opus: {
		ID:                       Claude48Opus,
		Name:                     "Claude 4.8 Opus",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-opus-4-8",
		CostPer1MIn:              5.0,
		CostPer1MInCached:        6.25,
		CostPer1MOutCached:       0.50,
		CostPer1MOut:             25.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude5Opus: {
		ID:                       Claude5Opus,
		Name:                     "Claude 5 Opus",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-opus-5",
		CostPer1MIn:              5.0,
		CostPer1MInCached:        6.25,
		CostPer1MOutCached:       0.50,
		CostPer1MOut:             25.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude55Opus: {
		ID:                       Claude55Opus,
		Name:                     "Claude 5.5 Opus",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-opus-5-5",
		CostPer1MIn:              4.0,
		CostPer1MInCached:        5.00,
		CostPer1MOutCached:       0.20,
		CostPer1MOut:             20.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
		RejectsForcedToolChoice:  true,
	},
	ClaudeFable5: {
		ID:                       ClaudeFable5,
		Name:                     "Claude Fable 5",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-fable-5",
		CostPer1MIn:              10.0,
		CostPer1MInCached:        12.50,
		CostPer1MOutCached:       1.00,
		CostPer1MOut:             50.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	ClaudeFable51: {
		ID:                       ClaudeFable51,
		Name:                     "Claude Fable 5.1",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-fable-5-1",
		CostPer1MIn:              10.0,
		CostPer1MInCached:        12.50,
		CostPer1MOutCached:       0.25,
		CostPer1MOut:             50.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
		RejectsForcedToolChoice:  true,
	},
	Claude46Sonnet: {
		ID:                       Claude46Sonnet,
		Name:                     "Claude 4.6 Sonnet",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-sonnet-4-6",
		CostPer1MIn:              3.0,
		CostPer1MInCached:        3.75,
		CostPer1MOutCached:       0.30,
		CostPer1MOut:             15.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude5Sonnet: {
		ID:                       Claude5Sonnet,
		Name:                     "Claude 5 Sonnet",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-sonnet-5",
		CostPer1MIn:              2.0,
		CostPer1MInCached:        2.50,
		CostPer1MOutCached:       0.20,
		CostPer1MOut:             10.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
	},
	Claude55Sonnet: {
		ID:                       Claude55Sonnet,
		Name:                     "Claude 5.5 Sonnet",
		Provider:                 ProviderAnthropic,
		APIModel:                 "claude-sonnet-5-5",
		CostPer1MIn:              2.0,
		CostPer1MInCached:        2.50,
		CostPer1MOutCached:       0.10, // 0.05x input, as on Opus 5.5
		CostPer1MOut:             10.0,
		ContextWindow:            1000000,
		DefaultMaxTokens:         128000,
		CanReason:                true,
		SupportsAdaptiveThinking: true,
		SupportsMaximumThinking:  true,
		SupportsXHighThinking:    true,
		SupportsTaskBudget:       true,
		SupportsToolSearch:       true,
		SupportsAttachments:      true,
		RejectsForcedToolChoice:  true,
	},
	Claude45Haiku: {
		ID:                  Claude45Haiku,
		Name:                "Claude 4.5 Haiku",
		Provider:            ProviderAnthropic,
		APIModel:            "claude-haiku-4-5-20251001",
		CostPer1MIn:         1.0,
		CostPer1MInCached:   1.25,
		CostPer1MOutCached:  0.10,
		CostPer1MOut:        5.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		SupportsToolSearch:  true,
		SupportsAttachments: true,
	},
	// Rates are for prompts up to 100K tokens; over that every rate is 5x.
	// Unlike Opus 5.5 and Sonnet 5.5, Haiku 5.5 accepts a forced tool_choice
	// (the turn then skips thinking), so RejectsForcedToolChoice stays unset.
	Claude55Haiku: {
		ID:                        Claude55Haiku,
		Name:                      "Claude 5.5 Haiku",
		Provider:                  ProviderAnthropic,
		APIModel:                  "claude-haiku-5-5",
		CostPer1MIn:               0.10,
		CostPer1MInCached:         0.125,
		CostPer1MOutCached:        0.01,
		CostPer1MOut:              0.50,
		LongContextThreshold:      100000,
		LongContextCostMultiplier: 5,
		ContextWindow:             1000000,
		DefaultMaxTokens:          128000,
		CanReason:                 true,
		SupportsAdaptiveThinking:  true,
		SupportsMaximumThinking:   true,
		SupportsXHighThinking:     true,
		SupportsTaskBudget:        true,
		SupportsToolSearch:        true,
		SupportsAttachments:       true,
		DefaultReasoningEffort:    ReasoningEffortMedium,
	},
}
