package models

const (
	ProviderVertexAI ModelProvider = "vertexai"

	// Models
	VertexAIGemini30Flash ModelID = "vertexai.gemini-3.0-flash"
	VertexAIGemini30Pro   ModelID = "vertexai.gemini-3.0-pro"
	VertexAISonnet45M     ModelID = "vertexai.claude-sonnet-4-5-m"
	VertexAIOpus45        ModelID = "vertexai.claude-opus-4-5"
	VertexAIOpus46        ModelID = "vertexai.claude-opus-4-6"
	VertexAIOpus47        ModelID = "vertexai.claude-opus-4-7"
	VertexAIOpus48        ModelID = "vertexai.claude-opus-4-8"
	VertexAISonnet46      ModelID = "vertexai.claude-sonnet-4-6"
	VertexAIHaiku45       ModelID = "vertexai.claude-haiku-4-5"
	VertexAIFable5        ModelID = "vertexai.claude-fable-5"
)

var VertexAIGeminiModels = map[ModelID]Model{
	VertexAIGemini30Pro: {
		ID:                  VertexAIGemini30Pro,
		Name:                "VertexAI: Gemini 3.0 Pro",
		Provider:            ProviderVertexAI,
		APIModel:            "gemini-3-pro-preview",
		CostPer1MIn:         GeminiModels[Gemini30Pro].CostPer1MIn,
		CostPer1MInCached:   GeminiModels[Gemini30Pro].CostPer1MInCached,
		CostPer1MOut:        GeminiModels[Gemini30Pro].CostPer1MOut,
		CostPer1MOutCached:  GeminiModels[Gemini30Pro].CostPer1MOutCached,
		ContextWindow:       GeminiModels[Gemini30Pro].ContextWindow,
		DefaultMaxTokens:    GeminiModels[Gemini30Pro].DefaultMaxTokens,
		SupportsAttachments: true,
		CanReason:           true,
	},
	VertexAIGemini30Flash: {
		ID:                  VertexAIGemini30Flash,
		Name:                "VertexAI: Gemini 3.0 Flash",
		Provider:            ProviderVertexAI,
		APIModel:            "gemini-3-flash-preview",
		CostPer1MIn:         GeminiModels[Gemini30Flash].CostPer1MIn,
		CostPer1MInCached:   GeminiModels[Gemini30Flash].CostPer1MInCached,
		CostPer1MOut:        GeminiModels[Gemini30Flash].CostPer1MOut,
		CostPer1MOutCached:  GeminiModels[Gemini30Flash].CostPer1MOutCached,
		ContextWindow:       GeminiModels[Gemini30Flash].ContextWindow,
		DefaultMaxTokens:    GeminiModels[Gemini30Flash].DefaultMaxTokens,
		SupportsAttachments: true,
		CanReason:           true,
	},
}

var VertexAIAnthropicModels = map[ModelID]Model{
	VertexAISonnet45M: {
		ID:                  VertexAISonnet45M,
		Name:                "VertexAI: Claude Sonnet 4.5 [1m]",
		Provider:            ProviderVertexAI,
		APIModel:            "claude-sonnet-4-5@20250929",
		CostPer1MIn:         AnthropicModels[Claude45Sonnet1M].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude45Sonnet1M].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude45Sonnet1M].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude45Sonnet1M].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude45Sonnet1M].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude45Sonnet1M].DefaultMaxTokens,
		SupportsAttachments: AnthropicModels[Claude45Sonnet1M].SupportsAttachments,
		CanReason:           AnthropicModels[Claude45Sonnet1M].CanReason,
	},
	VertexAIOpus45: {
		ID:                  VertexAIOpus45,
		Name:                "VertexAI: Claude Opus 4.5",
		Provider:            ProviderVertexAI,
		APIModel:            "claude-opus-4-5@20251101",
		CostPer1MIn:         AnthropicModels[Claude45Opus].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude45Opus].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude45Opus].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude45Opus].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude45Opus].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude45Opus].DefaultMaxTokens,
		SupportsAttachments: AnthropicModels[Claude45Opus].SupportsAttachments,
		CanReason:           AnthropicModels[Claude45Opus].CanReason,
	},
	VertexAIOpus46: {
		ID:                       VertexAIOpus46,
		Name:                     "VertexAI: Claude Opus 4.6",
		Provider:                 ProviderVertexAI,
		APIModel:                 "claude-opus-4-6",
		CostPer1MIn:              AnthropicModels[Claude46Opus].CostPer1MIn,
		CostPer1MInCached:        AnthropicModels[Claude46Opus].CostPer1MInCached,
		CostPer1MOut:             AnthropicModels[Claude46Opus].CostPer1MOut,
		CostPer1MOutCached:       AnthropicModels[Claude46Opus].CostPer1MOutCached,
		ContextWindow:            AnthropicModels[Claude46Opus].ContextWindow,
		DefaultMaxTokens:         AnthropicModels[Claude46Opus].DefaultMaxTokens,
		SupportsAttachments:      AnthropicModels[Claude46Opus].SupportsAttachments,
		CanReason:                AnthropicModels[Claude46Opus].CanReason,
		SupportsAdaptiveThinking: AnthropicModels[Claude46Opus].SupportsAdaptiveThinking,
		SupportsMaximumThinking:  AnthropicModels[Claude46Opus].SupportsMaximumThinking,
	},
	VertexAIOpus47: {
		ID:                       VertexAIOpus47,
		Name:                     "VertexAI: Claude Opus 4.7",
		Provider:                 ProviderVertexAI,
		APIModel:                 "claude-opus-4-7",
		CostPer1MIn:              AnthropicModels[Claude47Opus].CostPer1MIn,
		CostPer1MInCached:        AnthropicModels[Claude47Opus].CostPer1MInCached,
		CostPer1MOut:             AnthropicModels[Claude47Opus].CostPer1MOut,
		CostPer1MOutCached:       AnthropicModels[Claude47Opus].CostPer1MOutCached,
		ContextWindow:            AnthropicModels[Claude47Opus].ContextWindow,
		DefaultMaxTokens:         AnthropicModels[Claude47Opus].DefaultMaxTokens,
		SupportsAttachments:      AnthropicModels[Claude47Opus].SupportsAttachments,
		CanReason:                AnthropicModels[Claude47Opus].CanReason,
		SupportsAdaptiveThinking: AnthropicModels[Claude47Opus].SupportsAdaptiveThinking,
		SupportsMaximumThinking:  AnthropicModels[Claude47Opus].SupportsMaximumThinking,
		SupportsXHighThinking:    AnthropicModels[Claude47Opus].SupportsXHighThinking,
		SupportsTaskBudget:       AnthropicModels[Claude47Opus].SupportsTaskBudget,
	},
	VertexAIOpus48: {
		ID:                       VertexAIOpus48,
		Name:                     "VertexAI: Claude Opus 4.8",
		Provider:                 ProviderVertexAI,
		APIModel:                 "claude-opus-4-8",
		CostPer1MIn:              AnthropicModels[Claude48Opus].CostPer1MIn,
		CostPer1MInCached:        AnthropicModels[Claude48Opus].CostPer1MInCached,
		CostPer1MOut:             AnthropicModels[Claude48Opus].CostPer1MOut,
		CostPer1MOutCached:       AnthropicModels[Claude48Opus].CostPer1MOutCached,
		ContextWindow:            AnthropicModels[Claude48Opus].ContextWindow,
		DefaultMaxTokens:         AnthropicModels[Claude48Opus].DefaultMaxTokens,
		SupportsAttachments:      AnthropicModels[Claude48Opus].SupportsAttachments,
		CanReason:                AnthropicModels[Claude48Opus].CanReason,
		SupportsAdaptiveThinking: AnthropicModels[Claude48Opus].SupportsAdaptiveThinking,
		SupportsMaximumThinking:  AnthropicModels[Claude48Opus].SupportsMaximumThinking,
		SupportsXHighThinking:    AnthropicModels[Claude48Opus].SupportsXHighThinking,
		SupportsTaskBudget:       AnthropicModels[Claude48Opus].SupportsTaskBudget,
	},
	VertexAIFable5: {
		ID:                       VertexAIFable5,
		Name:                     "VertexAI: Claude Fable 5",
		Provider:                 ProviderVertexAI,
		APIModel:                 "claude-fable-5",
		CostPer1MIn:              AnthropicModels[ClaudeFable5].CostPer1MIn,
		CostPer1MInCached:        AnthropicModels[ClaudeFable5].CostPer1MInCached,
		CostPer1MOut:             AnthropicModels[ClaudeFable5].CostPer1MOut,
		CostPer1MOutCached:       AnthropicModels[ClaudeFable5].CostPer1MOutCached,
		ContextWindow:            AnthropicModels[ClaudeFable5].ContextWindow,
		DefaultMaxTokens:         AnthropicModels[ClaudeFable5].DefaultMaxTokens,
		SupportsAttachments:      AnthropicModels[ClaudeFable5].SupportsAttachments,
		CanReason:                AnthropicModels[ClaudeFable5].CanReason,
		SupportsAdaptiveThinking: AnthropicModels[ClaudeFable5].SupportsAdaptiveThinking,
		SupportsMaximumThinking:  AnthropicModels[ClaudeFable5].SupportsMaximumThinking,
		SupportsXHighThinking:    AnthropicModels[ClaudeFable5].SupportsXHighThinking,
		SupportsTaskBudget:       AnthropicModels[ClaudeFable5].SupportsTaskBudget,
	},
	VertexAISonnet46: {
		ID:                       VertexAISonnet46,
		Name:                     "VertexAI: Claude Sonnet 4.6",
		Provider:                 ProviderVertexAI,
		APIModel:                 "claude-sonnet-4-6",
		CostPer1MIn:              AnthropicModels[Claude46Sonnet].CostPer1MIn,
		CostPer1MInCached:        AnthropicModels[Claude46Sonnet].CostPer1MInCached,
		CostPer1MOut:             AnthropicModels[Claude46Sonnet].CostPer1MOut,
		CostPer1MOutCached:       AnthropicModels[Claude46Sonnet].CostPer1MOutCached,
		ContextWindow:            AnthropicModels[Claude46Sonnet].ContextWindow,
		DefaultMaxTokens:         AnthropicModels[Claude46Sonnet].DefaultMaxTokens,
		SupportsAttachments:      AnthropicModels[Claude46Sonnet].SupportsAttachments,
		CanReason:                AnthropicModels[Claude46Sonnet].CanReason,
		SupportsAdaptiveThinking: AnthropicModels[Claude46Sonnet].SupportsAdaptiveThinking,
	},
	VertexAIHaiku45: {
		ID:                  VertexAIHaiku45,
		Name:                "VertexAI: Claude Haiku 4.5",
		Provider:            ProviderVertexAI,
		APIModel:            "claude-haiku-4-5@20251001",
		CostPer1MIn:         AnthropicModels[Claude45Haiku].CostPer1MIn,
		CostPer1MInCached:   AnthropicModels[Claude45Haiku].CostPer1MInCached,
		CostPer1MOut:        AnthropicModels[Claude45Haiku].CostPer1MOut,
		CostPer1MOutCached:  AnthropicModels[Claude45Haiku].CostPer1MOutCached,
		ContextWindow:       AnthropicModels[Claude45Haiku].ContextWindow,
		DefaultMaxTokens:    AnthropicModels[Claude45Haiku].DefaultMaxTokens,
		SupportsAttachments: AnthropicModels[Claude45Haiku].SupportsAttachments,
	},
}
