// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cron_jobs.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const claimCronJobForFiring = `-- name: ClaimCronJobForFiring :execrows
UPDATE cron_jobs SET firing = TRUE
WHERE id = ?
  AND status = 'active'
  AND firing = FALSE
  AND next_run_at IS NOT NULL
  AND next_run_at <= ?
`

type ClaimCronJobForFiringParams struct {
	ID        string        `json:"id"`
	NextRunAt sql.NullInt64 `json:"next_run_at"`
}

// Atomically marks a cron job as firing only if it is still due. Returns the
// number of rows affected; 0 means another worker already claimed it or the
// row's next_run_at moved into the future.
func (q *Queries) ClaimCronJobForFiring(ctx context.Context, arg ClaimCronJobForFiringParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCronJobForFiring, arg.ID, arg.NextRunAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearStaleFiring = `-- name: ClearStaleFiring :exec
UPDATE cron_jobs SET firing = FALSE WHERE firing = TRUE
`

func (q *Queries) ClearStaleFiring(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearStaleFiring)
	return err
}

const countActiveCronJobsBySession = `-- name: CountActiveCronJobsBySession :one
SELECT COUNT(*) FROM cron_jobs
WHERE session_id = ? AND status = 'active'
`

func (q *Queries) CountActiveCronJobsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCronJobsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCronJob = `-- name: CreateCronJob :execresult
INSERT INTO cron_jobs (
    id,
    session_id,
    schedule,
    prompt,
    subagent_type,
    task_title,
    task_id,
    is_recurring,
    source,
    status,
    firing,
    next_run_at,
    run_count,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    FALSE,
    ?,
    0,
    UNIX_TIMESTAMP(),
    UNIX_TIMESTAMP()
)
`

type CreateCronJobParams struct {
	ID           string        `json:"id"`
	SessionID    string        `json:"session_id"`
	Schedule     string        `json:"schedule"`
	Prompt       string        `json:"prompt"`
	SubagentType string        `json:"subagent_type"`
	TaskTitle    string        `json:"task_title"`
	TaskID       string        `json:"task_id"`
	IsRecurring  bool          `json:"is_recurring"`
	Source       string        `json:"source"`
	Status       string        `json:"status"`
	NextRunAt    sql.NullInt64 `json:"next_run_at"`
}

func (q *Queries) CreateCronJob(ctx context.Context, arg CreateCronJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCronJob,
		arg.ID,
		arg.SessionID,
		arg.Schedule,
		arg.Prompt,
		arg.SubagentType,
		arg.TaskTitle,
		arg.TaskID,
		arg.IsRecurring,
		arg.Source,
		arg.Status,
		arg.NextRunAt,
	)
}

const deleteCronJob = `-- name: DeleteCronJob :exec
DELETE FROM cron_jobs WHERE id = ?
`

func (q *Queries) DeleteCronJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCronJob, id)
	return err
}

const getCronJob = `-- name: GetCronJob :one
SELECT id, session_id, schedule, prompt, subagent_type, task_title, task_id, is_recurring, source, status, firing, last_run_at, next_run_at, run_count, last_result, error, created_at, updated_at FROM cron_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetCronJob(ctx context.Context, id string) (CronJob, error) {
	row := q.db.QueryRowContext(ctx, getCronJob, id)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Schedule,
		&i.Prompt,
		&i.SubagentType,
		&i.TaskTitle,
		&i.TaskID,
		&i.IsRecurring,
		&i.Source,
		&i.Status,
		&i.Firing,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.RunCount,
		&i.LastResult,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCronJobs = `-- name: ListActiveCronJobs :many
SELECT id, session_id, schedule, prompt, subagent_type, task_title, task_id, is_recurring, source, status, firing, last_run_at, next_run_at, run_count, last_result, error, created_at, updated_at FROM cron_jobs WHERE status = 'active' ORDER BY created_at ASC
`

func (q *Queries) ListActiveCronJobs(ctx context.Context) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCronJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.SubagentType,
			&i.TaskTitle,
			&i.TaskID,
			&i.IsRecurring,
			&i.Source,
			&i.Status,
			&i.Firing,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.RunCount,
			&i.LastResult,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobsBySession = `-- name: ListCronJobsBySession :many
SELECT id, session_id, schedule, prompt, subagent_type, task_title, task_id, is_recurring, source, status, firing, last_run_at, next_run_at, run_count, last_result, error, created_at, updated_at FROM cron_jobs WHERE session_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListCronJobsBySession(ctx context.Context, sessionID string) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.SubagentType,
			&i.TaskTitle,
			&i.TaskID,
			&i.IsRecurring,
			&i.Source,
			&i.Status,
			&i.Firing,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.RunCount,
			&i.LastResult,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCronJobs = `-- name: ListDueCronJobs :many
SELECT id, session_id, schedule, prompt, subagent_type, task_title, task_id, is_recurring, source, status, firing, last_run_at, next_run_at, run_count, last_result, error, created_at, updated_at FROM cron_jobs
WHERE status = 'active'
  AND firing = FALSE
  AND next_run_at IS NOT NULL
  AND next_run_at <= ?
ORDER BY next_run_at ASC
`

func (q *Queries) ListDueCronJobs(ctx context.Context, nextRunAt sql.NullInt64) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listDueCronJobs, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.SubagentType,
			&i.TaskTitle,
			&i.TaskID,
			&i.IsRecurring,
			&i.Source,
			&i.Status,
			&i.Firing,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.RunCount,
			&i.LastResult,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissedOneShots = `-- name: ListMissedOneShots :many
SELECT id, session_id, schedule, prompt, subagent_type, task_title, task_id, is_recurring, source, status, firing, last_run_at, next_run_at, run_count, last_result, error, created_at, updated_at FROM cron_jobs
WHERE status = 'active'
  AND is_recurring = FALSE
  AND next_run_at IS NOT NULL
  AND next_run_at < ?
ORDER BY next_run_at ASC
`

func (q *Queries) ListMissedOneShots(ctx context.Context, nextRunAt sql.NullInt64) ([]CronJob, error) {
	rows, err := q.db.QueryContext(ctx, listMissedOneShots, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronJob{}
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Schedule,
			&i.Prompt,
			&i.SubagentType,
			&i.TaskTitle,
			&i.TaskID,
			&i.IsRecurring,
			&i.Source,
			&i.Status,
			&i.Firing,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.RunCount,
			&i.LastResult,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCronJobFiring = `-- name: SetCronJobFiring :exec
UPDATE cron_jobs SET firing = ? WHERE id = ?
`

type SetCronJobFiringParams struct {
	Firing bool   `json:"firing"`
	ID     string `json:"id"`
}

func (q *Queries) SetCronJobFiring(ctx context.Context, arg SetCronJobFiringParams) error {
	_, err := q.db.ExecContext(ctx, setCronJobFiring, arg.Firing, arg.ID)
	return err
}

const updateCronJobAfterRun = `-- name: UpdateCronJobAfterRun :execresult
UPDATE cron_jobs
SET last_run_at = ?,
    run_count = run_count + 1,
    last_result = ?,
    next_run_at = ?,
    status = ?,
    firing = FALSE,
    error = NULL
WHERE id = ?
`

type UpdateCronJobAfterRunParams struct {
	LastRunAt  sql.NullInt64  `json:"last_run_at"`
	LastResult sql.NullString `json:"last_result"`
	NextRunAt  sql.NullInt64  `json:"next_run_at"`
	Status     string         `json:"status"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateCronJobAfterRun(ctx context.Context, arg UpdateCronJobAfterRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCronJobAfterRun,
		arg.LastRunAt,
		arg.LastResult,
		arg.NextRunAt,
		arg.Status,
		arg.ID,
	)
}

const updateCronJobError = `-- name: UpdateCronJobError :exec
UPDATE cron_jobs SET error = ?, firing = FALSE WHERE id = ?
`

type UpdateCronJobErrorParams struct {
	Error sql.NullString `json:"error"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdateCronJobError(ctx context.Context, arg UpdateCronJobErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobError, arg.Error, arg.ID)
	return err
}

const updateCronJobNextRun = `-- name: UpdateCronJobNextRun :exec
UPDATE cron_jobs SET next_run_at = ? WHERE id = ?
`

type UpdateCronJobNextRunParams struct {
	NextRunAt sql.NullInt64 `json:"next_run_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateCronJobNextRun(ctx context.Context, arg UpdateCronJobNextRunParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobNextRun, arg.NextRunAt, arg.ID)
	return err
}

const updateCronJobStatus = `-- name: UpdateCronJobStatus :exec
UPDATE cron_jobs SET status = ? WHERE id = ?
`

type UpdateCronJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateCronJobStatus(ctx context.Context, arg UpdateCronJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobStatus, arg.Status, arg.ID)
	return err
}
