// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flow_states.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const createFlowState = `-- name: CreateFlowState :execresult
INSERT INTO flow_states (
    session_id,
    root_session_id,
    flow_id,
    step_id,
    status,
    args,
    output,
    is_struct_output,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    UNIX_TIMESTAMP(),
    UNIX_TIMESTAMP()
)
`

type CreateFlowStateParams struct {
	SessionID      string         `json:"session_id"`
	RootSessionID  string         `json:"root_session_id"`
	FlowID         string         `json:"flow_id"`
	StepID         string         `json:"step_id"`
	Status         string         `json:"status"`
	Args           sql.NullString `json:"args"`
	Output         sql.NullString `json:"output"`
	IsStructOutput bool           `json:"is_struct_output"`
}

func (q *Queries) CreateFlowState(ctx context.Context, arg CreateFlowStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFlowState,
		arg.SessionID,
		arg.RootSessionID,
		arg.FlowID,
		arg.StepID,
		arg.Status,
		arg.Args,
		arg.Output,
		arg.IsStructOutput,
	)
}

const deleteFlowStatesByRootSession = `-- name: DeleteFlowStatesByRootSession :exec
DELETE FROM flow_states WHERE root_session_id = ?
`

func (q *Queries) DeleteFlowStatesByRootSession(ctx context.Context, rootSessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteFlowStatesByRootSession, rootSessionID)
	return err
}

const getFlowState = `-- name: GetFlowState :one
SELECT session_id, root_session_id, flow_id, step_id, status, args, output, is_struct_output, created_at, updated_at FROM flow_states WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetFlowState(ctx context.Context, sessionID string) (FlowState, error) {
	row := q.db.QueryRowContext(ctx, getFlowState, sessionID)
	var i FlowState
	err := row.Scan(
		&i.SessionID,
		&i.RootSessionID,
		&i.FlowID,
		&i.StepID,
		&i.Status,
		&i.Args,
		&i.Output,
		&i.IsStructOutput,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlowStatesByFlowID = `-- name: ListFlowStatesByFlowID :many
SELECT session_id, root_session_id, flow_id, step_id, status, args, output, is_struct_output, created_at, updated_at FROM flow_states WHERE flow_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListFlowStatesByFlowID(ctx context.Context, flowID string) ([]FlowState, error) {
	rows, err := q.db.QueryContext(ctx, listFlowStatesByFlowID, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowState{}
	for rows.Next() {
		var i FlowState
		if err := rows.Scan(
			&i.SessionID,
			&i.RootSessionID,
			&i.FlowID,
			&i.StepID,
			&i.Status,
			&i.Args,
			&i.Output,
			&i.IsStructOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowStatesByRootSession = `-- name: ListFlowStatesByRootSession :many
SELECT session_id, root_session_id, flow_id, step_id, status, args, output, is_struct_output, created_at, updated_at FROM flow_states WHERE root_session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListFlowStatesByRootSession(ctx context.Context, rootSessionID string) ([]FlowState, error) {
	rows, err := q.db.QueryContext(ctx, listFlowStatesByRootSession, rootSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowState{}
	for rows.Next() {
		var i FlowState
		if err := rows.Scan(
			&i.SessionID,
			&i.RootSessionID,
			&i.FlowID,
			&i.StepID,
			&i.Status,
			&i.Args,
			&i.Output,
			&i.IsStructOutput,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowState = `-- name: UpdateFlowState :execresult
UPDATE flow_states
SET status = ?,
    output = ?,
    is_struct_output = ?
WHERE session_id = ?
`

type UpdateFlowStateParams struct {
	Status         string         `json:"status"`
	Output         sql.NullString `json:"output"`
	IsStructOutput bool           `json:"is_struct_output"`
	SessionID      string         `json:"session_id"`
}

func (q *Queries) UpdateFlowState(ctx context.Context, arg UpdateFlowStateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFlowState,
		arg.Status,
		arg.Output,
		arg.IsStructOutput,
		arg.SessionID,
	)
}
