// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysqldb

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Atomically marks a cron job as firing only if it is still due. Returns the
	// number of rows affected; 0 means another worker already claimed it or the
	// row's next_run_at moved into the future.
	ClaimCronJobForFiring(ctx context.Context, arg ClaimCronJobForFiringParams) (int64, error)
	ClearStaleFiring(ctx context.Context) error
	CountActiveCronJobsBySession(ctx context.Context, sessionID string) (int64, error)
	CreateCronJob(ctx context.Context, arg CreateCronJobParams) (sql.Result, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (sql.Result, error)
	CreateFlowState(ctx context.Context, arg CreateFlowStateParams) (sql.Result, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error)
	DeleteCronJob(ctx context.Context, id string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteFlowStatesByRootSession(ctx context.Context, rootSessionID string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteRecapBySessionID(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionTree(ctx context.Context, arg DeleteSessionTreeParams) error
	GetCronJob(ctx context.Context, id string) (CronJob, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFlowState(ctx context.Context, sessionID string) (FlowState, error)
	GetMaxSeqBySession(ctx context.Context, sessionID string) (int64, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecapBySessionID(ctx context.Context, sessionID string) (SessionRecap, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListActiveCronJobs(ctx context.Context) ([]CronJob, error)
	ListChildSessions(ctx context.Context, rootSessionID sql.NullString) ([]Session, error)
	ListCronJobsBySession(ctx context.Context, sessionID string) ([]CronJob, error)
	ListDueCronJobs(ctx context.Context, nextRunAt sql.NullInt64) ([]CronJob, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListFilesBySessionTree(ctx context.Context, rootSessionID sql.NullString) ([]File, error)
	ListFlowStatesByFlowID(ctx context.Context, flowID string) ([]FlowState, error)
	ListFlowStatesByRootSession(ctx context.Context, rootSessionID string) ([]FlowState, error)
	ListLatestMessagesBySession(ctx context.Context, arg ListLatestMessagesBySessionParams) ([]Message, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionTreeFiles(ctx context.Context, rootSessionID sql.NullString) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMissedOneShots(ctx context.Context, nextRunAt sql.NullInt64) ([]CronJob, error)
	ListSessions(ctx context.Context, projectID sql.NullString) ([]Session, error)
	SetCronJobFiring(ctx context.Context, arg SetCronJobFiringParams) error
	UpdateCronJobAfterRun(ctx context.Context, arg UpdateCronJobAfterRunParams) (sql.Result, error)
	UpdateCronJobError(ctx context.Context, arg UpdateCronJobErrorParams) error
	UpdateCronJobNextRun(ctx context.Context, arg UpdateCronJobNextRunParams) error
	UpdateCronJobStatus(ctx context.Context, arg UpdateCronJobStatusParams) error
	UpdateFile(ctx context.Context, arg UpdateFileParams) (sql.Result, error)
	UpdateFlowState(ctx context.Context, arg UpdateFlowStateParams) (sql.Result, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (sql.Result, error)
	UpsertRecap(ctx context.Context, arg UpsertRecapParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
