// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recaps.sql

package mysqldb

import (
	"context"
	"database/sql"
)

const deleteRecapBySessionID = `-- name: DeleteRecapBySessionID :exec
DELETE FROM session_recaps
WHERE session_id = ?
`

func (q *Queries) DeleteRecapBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecapBySessionID, sessionID)
	return err
}

const getRecapBySessionID = `-- name: GetRecapBySessionID :one
SELECT id, session_id, content, message_count, created_at
FROM session_recaps
WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetRecapBySessionID(ctx context.Context, sessionID string) (SessionRecap, error) {
	row := q.db.QueryRowContext(ctx, getRecapBySessionID, sessionID)
	var i SessionRecap
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRecap = `-- name: UpsertRecap :execresult
INSERT INTO session_recaps (
    id,
    session_id,
    content,
    message_count,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    UNIX_TIMESTAMP()
) ON DUPLICATE KEY UPDATE
    content = VALUES(content),
    message_count = VALUES(message_count),
    created_at = VALUES(created_at)
`

type UpsertRecapParams struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	Content      string `json:"content"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) UpsertRecap(ctx context.Context, arg UpsertRecapParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertRecap,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.MessageCount,
	)
}
