// Code generated by MockGen. DO NOT EDIT.
// Source: ./registry.go
//
// Generated by this command:
//
//	mockgen -source ./registry.go -destination ./mocks/agent_mock.go
//

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	reflect "reflect"

	agent "github.com/opencode-ai/opencode/internal/agent"
	config "github.com/opencode-ai/opencode/internal/config"
	permission "github.com/opencode-ai/opencode/internal/permission"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// EvaluatePermission mocks base method.
func (m *MockRegistry) EvaluatePermission(agentID, toolName, input string) permission.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluatePermission", agentID, toolName, input)
	ret0, _ := ret[0].(permission.Action)
	return ret0
}

// EvaluatePermission indicates an expected call of EvaluatePermission.
func (mr *MockRegistryMockRecorder) EvaluatePermission(agentID, toolName, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluatePermission", reflect.TypeOf((*MockRegistry)(nil).EvaluatePermission), agentID, toolName, input)
}

// EvaluateReadPermission mocks base method.
func (m *MockRegistry) EvaluateReadPermission(agentID, toolName, input string) permission.Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateReadPermission", agentID, toolName, input)
	ret0, _ := ret[0].(permission.Action)
	return ret0
}

// EvaluateReadPermission indicates an expected call of EvaluateReadPermission.
func (mr *MockRegistryMockRecorder) EvaluateReadPermission(agentID, toolName, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateReadPermission", reflect.TypeOf((*MockRegistry)(nil).EvaluateReadPermission), agentID, toolName, input)
}

// Get mocks base method.
func (m *MockRegistry) Get(id string) (agent.AgentInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(agent.AgentInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRegistryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistry)(nil).Get), id)
}

// GlobalPermissions mocks base method.
func (m *MockRegistry) GlobalPermissions() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalPermissions")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GlobalPermissions indicates an expected call of GlobalPermissions.
func (mr *MockRegistryMockRecorder) GlobalPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalPermissions", reflect.TypeOf((*MockRegistry)(nil).GlobalPermissions))
}

// HasTools mocks base method.
func (m *MockRegistry) HasTools(agentID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTools", agentID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTools indicates an expected call of HasTools.
func (mr *MockRegistryMockRecorder) HasTools(agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTools", reflect.TypeOf((*MockRegistry)(nil).HasTools), agentID)
}

// IsToolEnabled mocks base method.
func (m *MockRegistry) IsToolEnabled(agentID, toolName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsToolEnabled", agentID, toolName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsToolEnabled indicates an expected call of IsToolEnabled.
func (mr *MockRegistryMockRecorder) IsToolEnabled(agentID, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsToolEnabled", reflect.TypeOf((*MockRegistry)(nil).IsToolEnabled), agentID, toolName)
}

// List mocks base method.
func (m *MockRegistry) List() []agent.AgentInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]agent.AgentInfo)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRegistry)(nil).List))
}

// ListByMode mocks base method.
func (m *MockRegistry) ListByMode(mode config.AgentMode) []agent.AgentInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMode", mode)
	ret0, _ := ret[0].([]agent.AgentInfo)
	return ret0
}

// ListByMode indicates an expected call of ListByMode.
func (mr *MockRegistryMockRecorder) ListByMode(mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMode", reflect.TypeOf((*MockRegistry)(nil).ListByMode), mode)
}
