// Code generated by MockGen. DO NOT EDIT.
// Source: ./permission.go
//
// Generated by this command:
//
//	mockgen -source ./permission.go -destination ./mocks/permission_mock.go
//

// Package mock_permission is a generated GoMock package.
package mock_permission

import (
	context "context"
	reflect "reflect"

	permission "github.com/opencode-ai/opencode/internal/permission"
	pubsub "github.com/opencode-ai/opencode/internal/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AutoApproveSession mocks base method.
func (m *MockService) AutoApproveSession(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AutoApproveSession", sessionID)
}

// AutoApproveSession indicates an expected call of AutoApproveSession.
func (mr *MockServiceMockRecorder) AutoApproveSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoApproveSession", reflect.TypeOf((*MockService)(nil).AutoApproveSession), sessionID)
}

// Deny mocks base method.
func (m *MockService) Deny(arg0 permission.PermissionRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deny", arg0)
}

// Deny indicates an expected call of Deny.
func (mr *MockServiceMockRecorder) Deny(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockService)(nil).Deny), arg0)
}

// Grant mocks base method.
func (m *MockService) Grant(arg0 permission.PermissionRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Grant", arg0)
}

// Grant indicates an expected call of Grant.
func (mr *MockServiceMockRecorder) Grant(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MockService)(nil).Grant), arg0)
}

// GrantPersistant mocks base method.
func (m *MockService) GrantPersistant(arg0 permission.PermissionRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantPersistant", arg0)
}

// GrantPersistant indicates an expected call of GrantPersistant.
func (mr *MockServiceMockRecorder) GrantPersistant(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantPersistant", reflect.TypeOf((*MockService)(nil).GrantPersistant), arg0)
}

// IsAutoApproveSession mocks base method.
func (m *MockService) IsAutoApproveSession(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAutoApproveSession", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAutoApproveSession indicates an expected call of IsAutoApproveSession.
func (mr *MockServiceMockRecorder) IsAutoApproveSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAutoApproveSession", reflect.TypeOf((*MockService)(nil).IsAutoApproveSession), sessionID)
}

// Request mocks base method.
func (m *MockService) Request(opts permission.CreatePermissionRequest) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", opts)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockServiceMockRecorder) Request(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockService)(nil).Request), opts)
}

// Subscribe mocks base method.
func (m *MockService) Subscribe(arg0 context.Context) <-chan pubsub.Event[permission.PermissionRequest] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(<-chan pubsub.Event[permission.PermissionRequest])
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockServiceMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockService)(nil).Subscribe), arg0)
}
