// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bridge_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const countBridgeSessionsByIdentity = `-- name: CountBridgeSessionsByIdentity :one
SELECT COUNT(*)
FROM bridge_sessions
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
`

type CountBridgeSessionsByIdentityParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
}

func (q *Queries) CountBridgeSessionsByIdentity(ctx context.Context, arg CountBridgeSessionsByIdentityParams) (int64, error) {
	row := q.queryRow(ctx, q.countBridgeSessionsByIdentityStmt, countBridgeSessionsByIdentity, arg.ProjectID, arg.Channel, arg.IdentityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBridgeSessionByPeer = `-- name: DeleteBridgeSessionByPeer :exec
DELETE FROM bridge_sessions
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type DeleteBridgeSessionByPeerParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) DeleteBridgeSessionByPeer(ctx context.Context, arg DeleteBridgeSessionByPeerParams) error {
	_, err := q.exec(ctx, q.deleteBridgeSessionByPeerStmt, deleteBridgeSessionByPeer,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	return err
}

const deleteBridgeSessionsByIdentity = `-- name: DeleteBridgeSessionsByIdentity :exec
DELETE FROM bridge_sessions
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
`

type DeleteBridgeSessionsByIdentityParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
}

func (q *Queries) DeleteBridgeSessionsByIdentity(ctx context.Context, arg DeleteBridgeSessionsByIdentityParams) error {
	_, err := q.exec(ctx, q.deleteBridgeSessionsByIdentityStmt, deleteBridgeSessionsByIdentity, arg.ProjectID, arg.Channel, arg.IdentityID)
	return err
}

const deleteBridgeSessionsBySession = `-- name: DeleteBridgeSessionsBySession :exec
DELETE FROM bridge_sessions
WHERE project_id = ? AND session_id = ?
`

type DeleteBridgeSessionsBySessionParams struct {
	ProjectID string         `json:"project_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) DeleteBridgeSessionsBySession(ctx context.Context, arg DeleteBridgeSessionsBySessionParams) error {
	_, err := q.exec(ctx, q.deleteBridgeSessionsBySessionStmt, deleteBridgeSessionsBySession, arg.ProjectID, arg.SessionID)
	return err
}

const getBridgeSession = `-- name: GetBridgeSession :one
SELECT project_id, channel, identity_id, peer_id, session_id, mention_handle, mention_consumed_at, created_at, updated_at
FROM bridge_sessions
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
LIMIT 1
`

type GetBridgeSessionParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) GetBridgeSession(ctx context.Context, arg GetBridgeSessionParams) (BridgeSession, error) {
	row := q.queryRow(ctx, q.getBridgeSessionStmt, getBridgeSession,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	var i BridgeSession
	err := row.Scan(
		&i.ProjectID,
		&i.Channel,
		&i.IdentityID,
		&i.PeerID,
		&i.SessionID,
		&i.MentionHandle,
		&i.MentionConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBridgeSessionsByIdentity = `-- name: ListBridgeSessionsByIdentity :many
SELECT project_id, channel, identity_id, peer_id, session_id, mention_handle, mention_consumed_at, created_at, updated_at
FROM bridge_sessions
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
`

type ListBridgeSessionsByIdentityParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
}

func (q *Queries) ListBridgeSessionsByIdentity(ctx context.Context, arg ListBridgeSessionsByIdentityParams) ([]BridgeSession, error) {
	rows, err := q.query(ctx, q.listBridgeSessionsByIdentityStmt, listBridgeSessionsByIdentity, arg.ProjectID, arg.Channel, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeSession{}
	for rows.Next() {
		var i BridgeSession
		if err := rows.Scan(
			&i.ProjectID,
			&i.Channel,
			&i.IdentityID,
			&i.PeerID,
			&i.SessionID,
			&i.MentionHandle,
			&i.MentionConsumedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgeSessionsBySession = `-- name: ListBridgeSessionsBySession :many
SELECT project_id, channel, identity_id, peer_id, session_id, mention_handle, mention_consumed_at, created_at, updated_at
FROM bridge_sessions
WHERE project_id = ? AND session_id = ?
`

type ListBridgeSessionsBySessionParams struct {
	ProjectID string         `json:"project_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) ListBridgeSessionsBySession(ctx context.Context, arg ListBridgeSessionsBySessionParams) ([]BridgeSession, error) {
	rows, err := q.query(ctx, q.listBridgeSessionsBySessionStmt, listBridgeSessionsBySession, arg.ProjectID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeSession{}
	for rows.Next() {
		var i BridgeSession
		if err := rows.Scan(
			&i.ProjectID,
			&i.Channel,
			&i.IdentityID,
			&i.PeerID,
			&i.SessionID,
			&i.MentionHandle,
			&i.MentionConsumedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBridgeSessionMentionConsumed = `-- name: MarkBridgeSessionMentionConsumed :exec
UPDATE bridge_sessions
SET mention_consumed_at = strftime('%s','now'), updated_at = strftime('%s','now')
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type MarkBridgeSessionMentionConsumedParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) MarkBridgeSessionMentionConsumed(ctx context.Context, arg MarkBridgeSessionMentionConsumedParams) error {
	_, err := q.exec(ctx, q.markBridgeSessionMentionConsumedStmt, markBridgeSessionMentionConsumed,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	return err
}

const updateBridgeSessionPeerID = `-- name: UpdateBridgeSessionPeerID :exec
UPDATE bridge_sessions
SET peer_id = ?, updated_at = strftime('%s','now')
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type UpdateBridgeSessionPeerIDParams struct {
	PeerID     string `json:"peer_id"`
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID_2   string `json:"peer_id_2"`
}

func (q *Queries) UpdateBridgeSessionPeerID(ctx context.Context, arg UpdateBridgeSessionPeerIDParams) error {
	_, err := q.exec(ctx, q.updateBridgeSessionPeerIDStmt, updateBridgeSessionPeerID,
		arg.PeerID,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID_2,
	)
	return err
}

const updateBridgeSessionSessionID = `-- name: UpdateBridgeSessionSessionID :exec
UPDATE bridge_sessions
SET session_id = ?, updated_at = strftime('%s','now')
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type UpdateBridgeSessionSessionIDParams struct {
	SessionID  sql.NullString `json:"session_id"`
	ProjectID  string         `json:"project_id"`
	Channel    string         `json:"channel"`
	IdentityID string         `json:"identity_id"`
	PeerID     string         `json:"peer_id"`
}

func (q *Queries) UpdateBridgeSessionSessionID(ctx context.Context, arg UpdateBridgeSessionSessionIDParams) error {
	_, err := q.exec(ctx, q.updateBridgeSessionSessionIDStmt, updateBridgeSessionSessionID,
		arg.SessionID,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	return err
}

const upsertBridgeSession = `-- name: UpsertBridgeSession :one
INSERT INTO bridge_sessions (
    project_id,
    channel,
    identity_id,
    peer_id,
    session_id,
    mention_handle,
    mention_consumed_at,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    NULL,
    strftime('%s','now'),
    strftime('%s','now')
)
ON CONFLICT (project_id, channel, identity_id, peer_id) DO UPDATE
SET
    session_id          = excluded.session_id,
    mention_handle      = excluded.mention_handle,
    mention_consumed_at = NULL,
    updated_at          = strftime('%s','now')
RETURNING project_id, channel, identity_id, peer_id, session_id, mention_handle, mention_consumed_at, created_at, updated_at
`

type UpsertBridgeSessionParams struct {
	ProjectID     string         `json:"project_id"`
	Channel       string         `json:"channel"`
	IdentityID    string         `json:"identity_id"`
	PeerID        string         `json:"peer_id"`
	SessionID     sql.NullString `json:"session_id"`
	MentionHandle sql.NullString `json:"mention_handle"`
}

func (q *Queries) UpsertBridgeSession(ctx context.Context, arg UpsertBridgeSessionParams) (BridgeSession, error) {
	row := q.queryRow(ctx, q.upsertBridgeSessionStmt, upsertBridgeSession,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
		arg.SessionID,
		arg.MentionHandle,
	)
	var i BridgeSession
	err := row.Scan(
		&i.ProjectID,
		&i.Channel,
		&i.IdentityID,
		&i.PeerID,
		&i.SessionID,
		&i.MentionHandle,
		&i.MentionConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
