// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bridge_heartbeats.sql

package db

import (
	"context"
	"database/sql"
)

const getBridgeHeartbeat = `-- name: GetBridgeHeartbeat :one
SELECT project_id, channel, identity_id, peer_id, state, every_seconds, window_start, window_end, weekdays_only, model, agenda_file, next_beat_at, last_beat_at, last_status, last_error, reminded_at, updated_at
FROM bridge_heartbeats
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type GetBridgeHeartbeatParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) GetBridgeHeartbeat(ctx context.Context, arg GetBridgeHeartbeatParams) (BridgeHeartbeat, error) {
	row := q.queryRow(ctx, q.getBridgeHeartbeatStmt, getBridgeHeartbeat,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	var i BridgeHeartbeat
	err := row.Scan(
		&i.ProjectID,
		&i.Channel,
		&i.IdentityID,
		&i.PeerID,
		&i.State,
		&i.EverySeconds,
		&i.WindowStart,
		&i.WindowEnd,
		&i.WeekdaysOnly,
		&i.Model,
		&i.AgendaFile,
		&i.NextBeatAt,
		&i.LastBeatAt,
		&i.LastStatus,
		&i.LastError,
		&i.RemindedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBridgeHeartbeats = `-- name: ListBridgeHeartbeats :many
SELECT project_id, channel, identity_id, peer_id, state, every_seconds, window_start, window_end, weekdays_only, model, agenda_file, next_beat_at, last_beat_at, last_status, last_error, reminded_at, updated_at
FROM bridge_heartbeats
WHERE project_id = ?
`

func (q *Queries) ListBridgeHeartbeats(ctx context.Context, projectID string) ([]BridgeHeartbeat, error) {
	rows, err := q.query(ctx, q.listBridgeHeartbeatsStmt, listBridgeHeartbeats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeHeartbeat{}
	for rows.Next() {
		var i BridgeHeartbeat
		if err := rows.Scan(
			&i.ProjectID,
			&i.Channel,
			&i.IdentityID,
			&i.PeerID,
			&i.State,
			&i.EverySeconds,
			&i.WindowStart,
			&i.WindowEnd,
			&i.WeekdaysOnly,
			&i.Model,
			&i.AgendaFile,
			&i.NextBeatAt,
			&i.LastBeatAt,
			&i.LastStatus,
			&i.LastError,
			&i.RemindedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBridgeHeartbeat = `-- name: UpsertBridgeHeartbeat :exec
INSERT INTO bridge_heartbeats (
    project_id, channel, identity_id, peer_id, state, every_seconds, window_start, window_end, weekdays_only, model, agenda_file, next_beat_at, last_beat_at, last_status, last_error, reminded_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (project_id, channel, identity_id, peer_id) DO UPDATE SET
    state         = excluded.state,
    every_seconds = excluded.every_seconds,
    window_start  = excluded.window_start,
    window_end    = excluded.window_end,
    weekdays_only = excluded.weekdays_only,
    model         = excluded.model,
    agenda_file   = excluded.agenda_file,
    next_beat_at  = excluded.next_beat_at,
    last_beat_at  = excluded.last_beat_at,
    last_status   = excluded.last_status,
    last_error    = excluded.last_error,
    reminded_at   = excluded.reminded_at,
    updated_at    = excluded.updated_at
`

type UpsertBridgeHeartbeatParams struct {
	ProjectID    string         `json:"project_id"`
	Channel      string         `json:"channel"`
	IdentityID   string         `json:"identity_id"`
	PeerID       string         `json:"peer_id"`
	State        string         `json:"state"`
	EverySeconds sql.NullInt64  `json:"every_seconds"`
	WindowStart  sql.NullInt64  `json:"window_start"`
	WindowEnd    sql.NullInt64  `json:"window_end"`
	WeekdaysOnly int64          `json:"weekdays_only"`
	Model        sql.NullString `json:"model"`
	AgendaFile   sql.NullString `json:"agenda_file"`
	NextBeatAt   sql.NullInt64  `json:"next_beat_at"`
	LastBeatAt   sql.NullInt64  `json:"last_beat_at"`
	LastStatus   sql.NullString `json:"last_status"`
	LastError    sql.NullString `json:"last_error"`
	RemindedAt   sql.NullInt64  `json:"reminded_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) UpsertBridgeHeartbeat(ctx context.Context, arg UpsertBridgeHeartbeatParams) error {
	_, err := q.exec(ctx, q.upsertBridgeHeartbeatStmt, upsertBridgeHeartbeat,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
		arg.State,
		arg.EverySeconds,
		arg.WindowStart,
		arg.WindowEnd,
		arg.WeekdaysOnly,
		arg.Model,
		arg.AgendaFile,
		arg.NextBeatAt,
		arg.LastBeatAt,
		arg.LastStatus,
		arg.LastError,
		arg.RemindedAt,
		arg.UpdatedAt,
	)
	return err
}
