// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bridge_allowlist.sql

package db

import (
	"context"
)

const addBridgeAllowlistEntry = `-- name: AddBridgeAllowlistEntry :exec
INSERT INTO bridge_allowlist (
    project_id,
    channel,
    identity_id,
    peer_id,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%s','now')
)
ON CONFLICT (project_id, channel, identity_id, peer_id) DO NOTHING
`

type AddBridgeAllowlistEntryParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) AddBridgeAllowlistEntry(ctx context.Context, arg AddBridgeAllowlistEntryParams) error {
	_, err := q.exec(ctx, q.addBridgeAllowlistEntryStmt, addBridgeAllowlistEntry,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	return err
}

const isBridgeAllowlisted = `-- name: IsBridgeAllowlisted :one
SELECT EXISTS(
    SELECT 1 FROM bridge_allowlist
    WHERE project_id  = ?
      AND channel     = ?
      AND identity_id = ?
      AND peer_id     = ?
) AS allowed
`

type IsBridgeAllowlistedParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) IsBridgeAllowlisted(ctx context.Context, arg IsBridgeAllowlistedParams) (int64, error) {
	row := q.queryRow(ctx, q.isBridgeAllowlistedStmt, isBridgeAllowlisted,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	var allowed int64
	err := row.Scan(&allowed)
	return allowed, err
}

const listBridgeAllowlist = `-- name: ListBridgeAllowlist :many
SELECT project_id, channel, identity_id, peer_id, created_at
FROM bridge_allowlist
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
ORDER BY created_at ASC
`

type ListBridgeAllowlistParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
}

func (q *Queries) ListBridgeAllowlist(ctx context.Context, arg ListBridgeAllowlistParams) ([]BridgeAllowlist, error) {
	rows, err := q.query(ctx, q.listBridgeAllowlistStmt, listBridgeAllowlist, arg.ProjectID, arg.Channel, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BridgeAllowlist{}
	for rows.Next() {
		var i BridgeAllowlist
		if err := rows.Scan(
			&i.ProjectID,
			&i.Channel,
			&i.IdentityID,
			&i.PeerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBridgeAllowlistEntry = `-- name: RemoveBridgeAllowlistEntry :exec
DELETE FROM bridge_allowlist
WHERE project_id  = ?
  AND channel     = ?
  AND identity_id = ?
  AND peer_id     = ?
`

type RemoveBridgeAllowlistEntryParams struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
}

func (q *Queries) RemoveBridgeAllowlistEntry(ctx context.Context, arg RemoveBridgeAllowlistEntryParams) error {
	_, err := q.exec(ctx, q.removeBridgeAllowlistEntryStmt, removeBridgeAllowlistEntry,
		arg.ProjectID,
		arg.Channel,
		arg.IdentityID,
		arg.PeerID,
	)
	return err
}
