// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.claimCronJobForFiringStmt, err = db.PrepareContext(ctx, claimCronJobForFiring); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimCronJobForFiring: %w", err)
	}
	if q.clearStaleFiringStmt, err = db.PrepareContext(ctx, clearStaleFiring); err != nil {
		return nil, fmt.Errorf("error preparing query ClearStaleFiring: %w", err)
	}
	if q.countActiveCronJobsBySessionStmt, err = db.PrepareContext(ctx, countActiveCronJobsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountActiveCronJobsBySession: %w", err)
	}
	if q.createCronJobStmt, err = db.PrepareContext(ctx, createCronJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCronJob: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createFlowStateStmt, err = db.PrepareContext(ctx, createFlowState); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFlowState: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteCronJobStmt, err = db.PrepareContext(ctx, deleteCronJob); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCronJob: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteFlowStatesByRootSessionStmt, err = db.PrepareContext(ctx, deleteFlowStatesByRootSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFlowStatesByRootSession: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteRecapBySessionIDStmt, err = db.PrepareContext(ctx, deleteRecapBySessionID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRecapBySessionID: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteSessionTreeStmt, err = db.PrepareContext(ctx, deleteSessionTree); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionTree: %w", err)
	}
	if q.getCronJobStmt, err = db.PrepareContext(ctx, getCronJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetCronJob: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFlowStateStmt, err = db.PrepareContext(ctx, getFlowState); err != nil {
		return nil, fmt.Errorf("error preparing query GetFlowState: %w", err)
	}
	if q.getMaxSeqBySessionStmt, err = db.PrepareContext(ctx, getMaxSeqBySession); err != nil {
		return nil, fmt.Errorf("error preparing query GetMaxSeqBySession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getRecapBySessionIDStmt, err = db.PrepareContext(ctx, getRecapBySessionID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecapBySessionID: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.listActiveCronJobsStmt, err = db.PrepareContext(ctx, listActiveCronJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveCronJobs: %w", err)
	}
	if q.listChildSessionsStmt, err = db.PrepareContext(ctx, listChildSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListChildSessions: %w", err)
	}
	if q.listCronJobsBySessionStmt, err = db.PrepareContext(ctx, listCronJobsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListCronJobsBySession: %w", err)
	}
	if q.listDueCronJobsStmt, err = db.PrepareContext(ctx, listDueCronJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListDueCronJobs: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listFilesBySessionTreeStmt, err = db.PrepareContext(ctx, listFilesBySessionTree); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySessionTree: %w", err)
	}
	if q.listFlowStatesByFlowIDStmt, err = db.PrepareContext(ctx, listFlowStatesByFlowID); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowStatesByFlowID: %w", err)
	}
	if q.listFlowStatesByRootSessionStmt, err = db.PrepareContext(ctx, listFlowStatesByRootSession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFlowStatesByRootSession: %w", err)
	}
	if q.listLatestMessagesBySessionStmt, err = db.PrepareContext(ctx, listLatestMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestMessagesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listLatestSessionTreeFilesStmt, err = db.PrepareContext(ctx, listLatestSessionTreeFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionTreeFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMissedOneShotsStmt, err = db.PrepareContext(ctx, listMissedOneShots); err != nil {
		return nil, fmt.Errorf("error preparing query ListMissedOneShots: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.setCronJobFiringStmt, err = db.PrepareContext(ctx, setCronJobFiring); err != nil {
		return nil, fmt.Errorf("error preparing query SetCronJobFiring: %w", err)
	}
	if q.updateCronJobAfterRunStmt, err = db.PrepareContext(ctx, updateCronJobAfterRun); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCronJobAfterRun: %w", err)
	}
	if q.updateCronJobErrorStmt, err = db.PrepareContext(ctx, updateCronJobError); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCronJobError: %w", err)
	}
	if q.updateCronJobNextRunStmt, err = db.PrepareContext(ctx, updateCronJobNextRun); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCronJobNextRun: %w", err)
	}
	if q.updateCronJobStatusStmt, err = db.PrepareContext(ctx, updateCronJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCronJobStatus: %w", err)
	}
	if q.updateFileStmt, err = db.PrepareContext(ctx, updateFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFile: %w", err)
	}
	if q.updateFlowStateStmt, err = db.PrepareContext(ctx, updateFlowState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFlowState: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.upsertRecapStmt, err = db.PrepareContext(ctx, upsertRecap); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertRecap: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.claimCronJobForFiringStmt != nil {
		if cerr := q.claimCronJobForFiringStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimCronJobForFiringStmt: %w", cerr)
		}
	}
	if q.clearStaleFiringStmt != nil {
		if cerr := q.clearStaleFiringStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearStaleFiringStmt: %w", cerr)
		}
	}
	if q.countActiveCronJobsBySessionStmt != nil {
		if cerr := q.countActiveCronJobsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countActiveCronJobsBySessionStmt: %w", cerr)
		}
	}
	if q.createCronJobStmt != nil {
		if cerr := q.createCronJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCronJobStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createFlowStateStmt != nil {
		if cerr := q.createFlowStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFlowStateStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteCronJobStmt != nil {
		if cerr := q.deleteCronJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCronJobStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteFlowStatesByRootSessionStmt != nil {
		if cerr := q.deleteFlowStatesByRootSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFlowStatesByRootSessionStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteRecapBySessionIDStmt != nil {
		if cerr := q.deleteRecapBySessionIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRecapBySessionIDStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteSessionTreeStmt != nil {
		if cerr := q.deleteSessionTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionTreeStmt: %w", cerr)
		}
	}
	if q.getCronJobStmt != nil {
		if cerr := q.getCronJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCronJobStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFlowStateStmt != nil {
		if cerr := q.getFlowStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFlowStateStmt: %w", cerr)
		}
	}
	if q.getMaxSeqBySessionStmt != nil {
		if cerr := q.getMaxSeqBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMaxSeqBySessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getRecapBySessionIDStmt != nil {
		if cerr := q.getRecapBySessionIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecapBySessionIDStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.listActiveCronJobsStmt != nil {
		if cerr := q.listActiveCronJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveCronJobsStmt: %w", cerr)
		}
	}
	if q.listChildSessionsStmt != nil {
		if cerr := q.listChildSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listChildSessionsStmt: %w", cerr)
		}
	}
	if q.listCronJobsBySessionStmt != nil {
		if cerr := q.listCronJobsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCronJobsBySessionStmt: %w", cerr)
		}
	}
	if q.listDueCronJobsStmt != nil {
		if cerr := q.listDueCronJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDueCronJobsStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionTreeStmt != nil {
		if cerr := q.listFilesBySessionTreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionTreeStmt: %w", cerr)
		}
	}
	if q.listFlowStatesByFlowIDStmt != nil {
		if cerr := q.listFlowStatesByFlowIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowStatesByFlowIDStmt: %w", cerr)
		}
	}
	if q.listFlowStatesByRootSessionStmt != nil {
		if cerr := q.listFlowStatesByRootSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFlowStatesByRootSessionStmt: %w", cerr)
		}
	}
	if q.listLatestMessagesBySessionStmt != nil {
		if cerr := q.listLatestMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listLatestSessionTreeFilesStmt != nil {
		if cerr := q.listLatestSessionTreeFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionTreeFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMissedOneShotsStmt != nil {
		if cerr := q.listMissedOneShotsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMissedOneShotsStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.setCronJobFiringStmt != nil {
		if cerr := q.setCronJobFiringStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setCronJobFiringStmt: %w", cerr)
		}
	}
	if q.updateCronJobAfterRunStmt != nil {
		if cerr := q.updateCronJobAfterRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCronJobAfterRunStmt: %w", cerr)
		}
	}
	if q.updateCronJobErrorStmt != nil {
		if cerr := q.updateCronJobErrorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCronJobErrorStmt: %w", cerr)
		}
	}
	if q.updateCronJobNextRunStmt != nil {
		if cerr := q.updateCronJobNextRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCronJobNextRunStmt: %w", cerr)
		}
	}
	if q.updateCronJobStatusStmt != nil {
		if cerr := q.updateCronJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCronJobStatusStmt: %w", cerr)
		}
	}
	if q.updateFileStmt != nil {
		if cerr := q.updateFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFileStmt: %w", cerr)
		}
	}
	if q.updateFlowStateStmt != nil {
		if cerr := q.updateFlowStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFlowStateStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.upsertRecapStmt != nil {
		if cerr := q.upsertRecapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertRecapStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	claimCronJobForFiringStmt         *sql.Stmt
	clearStaleFiringStmt              *sql.Stmt
	countActiveCronJobsBySessionStmt  *sql.Stmt
	createCronJobStmt                 *sql.Stmt
	createFileStmt                    *sql.Stmt
	createFlowStateStmt               *sql.Stmt
	createMessageStmt                 *sql.Stmt
	createSessionStmt                 *sql.Stmt
	deleteCronJobStmt                 *sql.Stmt
	deleteFileStmt                    *sql.Stmt
	deleteFlowStatesByRootSessionStmt *sql.Stmt
	deleteMessageStmt                 *sql.Stmt
	deleteRecapBySessionIDStmt        *sql.Stmt
	deleteSessionStmt                 *sql.Stmt
	deleteSessionFilesStmt            *sql.Stmt
	deleteSessionMessagesStmt         *sql.Stmt
	deleteSessionTreeStmt             *sql.Stmt
	getCronJobStmt                    *sql.Stmt
	getFileStmt                       *sql.Stmt
	getFileByPathAndSessionStmt       *sql.Stmt
	getFlowStateStmt                  *sql.Stmt
	getMaxSeqBySessionStmt            *sql.Stmt
	getMessageStmt                    *sql.Stmt
	getRecapBySessionIDStmt           *sql.Stmt
	getSessionByIDStmt                *sql.Stmt
	listActiveCronJobsStmt            *sql.Stmt
	listChildSessionsStmt             *sql.Stmt
	listCronJobsBySessionStmt         *sql.Stmt
	listDueCronJobsStmt               *sql.Stmt
	listFilesByPathStmt               *sql.Stmt
	listFilesBySessionStmt            *sql.Stmt
	listFilesBySessionTreeStmt        *sql.Stmt
	listFlowStatesByFlowIDStmt        *sql.Stmt
	listFlowStatesByRootSessionStmt   *sql.Stmt
	listLatestMessagesBySessionStmt   *sql.Stmt
	listLatestSessionFilesStmt        *sql.Stmt
	listLatestSessionTreeFilesStmt    *sql.Stmt
	listMessagesBySessionStmt         *sql.Stmt
	listMissedOneShotsStmt            *sql.Stmt
	listSessionsStmt                  *sql.Stmt
	setCronJobFiringStmt              *sql.Stmt
	updateCronJobAfterRunStmt         *sql.Stmt
	updateCronJobErrorStmt            *sql.Stmt
	updateCronJobNextRunStmt          *sql.Stmt
	updateCronJobStatusStmt           *sql.Stmt
	updateFileStmt                    *sql.Stmt
	updateFlowStateStmt               *sql.Stmt
	updateMessageStmt                 *sql.Stmt
	updateSessionStmt                 *sql.Stmt
	upsertRecapStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		claimCronJobForFiringStmt:         q.claimCronJobForFiringStmt,
		clearStaleFiringStmt:              q.clearStaleFiringStmt,
		countActiveCronJobsBySessionStmt:  q.countActiveCronJobsBySessionStmt,
		createCronJobStmt:                 q.createCronJobStmt,
		createFileStmt:                    q.createFileStmt,
		createFlowStateStmt:               q.createFlowStateStmt,
		createMessageStmt:                 q.createMessageStmt,
		createSessionStmt:                 q.createSessionStmt,
		deleteCronJobStmt:                 q.deleteCronJobStmt,
		deleteFileStmt:                    q.deleteFileStmt,
		deleteFlowStatesByRootSessionStmt: q.deleteFlowStatesByRootSessionStmt,
		deleteMessageStmt:                 q.deleteMessageStmt,
		deleteRecapBySessionIDStmt:        q.deleteRecapBySessionIDStmt,
		deleteSessionStmt:                 q.deleteSessionStmt,
		deleteSessionFilesStmt:            q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:         q.deleteSessionMessagesStmt,
		deleteSessionTreeStmt:             q.deleteSessionTreeStmt,
		getCronJobStmt:                    q.getCronJobStmt,
		getFileStmt:                       q.getFileStmt,
		getFileByPathAndSessionStmt:       q.getFileByPathAndSessionStmt,
		getFlowStateStmt:                  q.getFlowStateStmt,
		getMaxSeqBySessionStmt:            q.getMaxSeqBySessionStmt,
		getMessageStmt:                    q.getMessageStmt,
		getRecapBySessionIDStmt:           q.getRecapBySessionIDStmt,
		getSessionByIDStmt:                q.getSessionByIDStmt,
		listActiveCronJobsStmt:            q.listActiveCronJobsStmt,
		listChildSessionsStmt:             q.listChildSessionsStmt,
		listCronJobsBySessionStmt:         q.listCronJobsBySessionStmt,
		listDueCronJobsStmt:               q.listDueCronJobsStmt,
		listFilesByPathStmt:               q.listFilesByPathStmt,
		listFilesBySessionStmt:            q.listFilesBySessionStmt,
		listFilesBySessionTreeStmt:        q.listFilesBySessionTreeStmt,
		listFlowStatesByFlowIDStmt:        q.listFlowStatesByFlowIDStmt,
		listFlowStatesByRootSessionStmt:   q.listFlowStatesByRootSessionStmt,
		listLatestMessagesBySessionStmt:   q.listLatestMessagesBySessionStmt,
		listLatestSessionFilesStmt:        q.listLatestSessionFilesStmt,
		listLatestSessionTreeFilesStmt:    q.listLatestSessionTreeFilesStmt,
		listMessagesBySessionStmt:         q.listMessagesBySessionStmt,
		listMissedOneShotsStmt:            q.listMissedOneShotsStmt,
		listSessionsStmt:                  q.listSessionsStmt,
		setCronJobFiringStmt:              q.setCronJobFiringStmt,
		updateCronJobAfterRunStmt:         q.updateCronJobAfterRunStmt,
		updateCronJobErrorStmt:            q.updateCronJobErrorStmt,
		updateCronJobNextRunStmt:          q.updateCronJobNextRunStmt,
		updateCronJobStatusStmt:           q.updateCronJobStatusStmt,
		updateFileStmt:                    q.updateFileStmt,
		updateFlowStateStmt:               q.updateFlowStateStmt,
		updateMessageStmt:                 q.updateMessageStmt,
		updateSessionStmt:                 q.updateSessionStmt,
		upsertRecapStmt:                   q.upsertRecapStmt,
	}
}
