// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type BridgeAllowlist struct {
	ProjectID  string `json:"project_id"`
	Channel    string `json:"channel"`
	IdentityID string `json:"identity_id"`
	PeerID     string `json:"peer_id"`
	CreatedAt  int64  `json:"created_at"`
}

type BridgeSession struct {
	ProjectID         string         `json:"project_id"`
	Channel           string         `json:"channel"`
	IdentityID        string         `json:"identity_id"`
	PeerID            string         `json:"peer_id"`
	SessionID         sql.NullString `json:"session_id"`
	MentionHandle     sql.NullString `json:"mention_handle"`
	MentionConsumedAt sql.NullInt64  `json:"mention_consumed_at"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

type CronJob struct {
	ID           string         `json:"id"`
	SessionID    string         `json:"session_id"`
	Schedule     string         `json:"schedule"`
	Prompt       string         `json:"prompt"`
	SubagentType string         `json:"subagent_type"`
	TaskTitle    string         `json:"task_title"`
	TaskID       string         `json:"task_id"`
	IsRecurring  bool           `json:"is_recurring"`
	Source       string         `json:"source"`
	Status       string         `json:"status"`
	Firing       bool           `json:"firing"`
	LastRunAt    sql.NullInt64  `json:"last_run_at"`
	NextRunAt    sql.NullInt64  `json:"next_run_at"`
	RunCount     int64          `json:"run_count"`
	LastResult   sql.NullString `json:"last_result"`
	Error        sql.NullString `json:"error"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   string `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type FlowState struct {
	SessionID      string         `json:"session_id"`
	RootSessionID  string         `json:"root_session_id"`
	FlowID         string         `json:"flow_id"`
	StepID         string         `json:"step_id"`
	Status         string         `json:"status"`
	Args           sql.NullString `json:"args"`
	Output         sql.NullString `json:"output"`
	IsStructOutput bool           `json:"is_struct_output"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	Iteration      int64          `json:"iteration"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	Seq        sql.NullInt64  `json:"seq"`
}

type Session struct {
	ID                    string         `json:"id"`
	ParentSessionID       sql.NullString `json:"parent_session_id"`
	Title                 string         `json:"title"`
	MessageCount          int64          `json:"message_count"`
	PromptTokens          int64          `json:"prompt_tokens"`
	CompletionTokens      int64          `json:"completion_tokens"`
	Cost                  float64        `json:"cost"`
	UpdatedAt             int64          `json:"updated_at"`
	CreatedAt             int64          `json:"created_at"`
	SummaryMessageID      sql.NullString `json:"summary_message_id"`
	ProjectID             sql.NullString `json:"project_id"`
	RootSessionID         sql.NullString `json:"root_session_id"`
	TotalPromptTokens     int64          `json:"total_prompt_tokens"`
	TotalCompletionTokens int64          `json:"total_completion_tokens"`
}

type SessionRecap struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	Content      string `json:"content"`
	MessageCount int64  `json:"message_count"`
	CreatedAt    int64  `json:"created_at"`
}
