// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recaps.sql

package db

import (
	"context"
)

const deleteRecapBySessionID = `-- name: DeleteRecapBySessionID :exec
DELETE FROM session_recaps
WHERE session_id = ?
`

func (q *Queries) DeleteRecapBySessionID(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteRecapBySessionIDStmt, deleteRecapBySessionID, sessionID)
	return err
}

const getRecapBySessionID = `-- name: GetRecapBySessionID :one
SELECT id, session_id, content, message_count, created_at
FROM session_recaps
WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetRecapBySessionID(ctx context.Context, sessionID string) (SessionRecap, error) {
	row := q.queryRow(ctx, q.getRecapBySessionIDStmt, getRecapBySessionID, sessionID)
	var i SessionRecap
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRecap = `-- name: UpsertRecap :one
INSERT INTO session_recaps (
    id,
    session_id,
    content,
    message_count,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now')
) ON CONFLICT(session_id) DO UPDATE SET
    content = excluded.content,
    message_count = excluded.message_count,
    created_at = excluded.created_at
RETURNING id, session_id, content, message_count, created_at
`

type UpsertRecapParams struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	Content      string `json:"content"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) UpsertRecap(ctx context.Context, arg UpsertRecapParams) (SessionRecap, error) {
	row := q.queryRow(ctx, q.upsertRecapStmt, upsertRecap,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.MessageCount,
	)
	var i SessionRecap
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.MessageCount,
		&i.CreatedAt,
	)
	return i, err
}
