// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    project_id,
    parent_session_id,
    root_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	ProjectID        sql.NullString `json:"project_id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	RootSessionID    sql.NullString `json:"root_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ProjectID,
		arg.ParentSessionID,
		arg.RootSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.UserSetTitle,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const deleteSessionTree = `-- name: DeleteSessionTree :exec
DELETE FROM sessions
WHERE id = ? OR root_session_id = ?
`

type DeleteSessionTreeParams struct {
	ID            string         `json:"id"`
	RootSessionID sql.NullString `json:"root_session_id"`
}

func (q *Queries) DeleteSessionTree(ctx context.Context, arg DeleteSessionTreeParams) error {
	_, err := q.exec(ctx, q.deleteSessionTreeStmt, deleteSessionTree, arg.ID, arg.RootSessionID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.UserSetTitle,
	)
	return i, err
}

const listChildSessions = `-- name: ListChildSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
FROM sessions
WHERE root_session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListChildSessions(ctx context.Context, rootSessionID sql.NullString) ([]Session, error) {
	rows, err := q.query(ctx, q.listChildSessionsStmt, listChildSessions, rootSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.ProjectID,
			&i.RootSessionID,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.UserSetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
FROM sessions
WHERE parent_session_id is NULL AND project_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, projectID sql.NullString) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.ProjectID,
			&i.RootSessionID,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.UserSetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :one
UPDATE sessions
SET
    title = ?,
    user_set_title = TRUE
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.UserSetTitle,
	)
	return i, err
}

const setGeneratedTitle = `-- name: SetGeneratedTitle :execrows
UPDATE sessions
SET title = ?
WHERE id = ? AND user_set_title = FALSE
`

type SetGeneratedTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) SetGeneratedTitle(ctx context.Context, arg SetGeneratedTitleParams) (int64, error) {
	result, err := q.exec(ctx, q.setGeneratedTitleStmt, setGeneratedTitle, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    total_prompt_tokens = ?,
    total_completion_tokens = ?,
    summary_message_id = ?,
    cost = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, project_id, root_session_id, total_prompt_tokens, total_completion_tokens, user_set_title
`

type UpdateSessionParams struct {
	Title                 string         `json:"title"`
	PromptTokens          int64          `json:"prompt_tokens"`
	CompletionTokens      int64          `json:"completion_tokens"`
	TotalPromptTokens     int64          `json:"total_prompt_tokens"`
	TotalCompletionTokens int64          `json:"total_completion_tokens"`
	SummaryMessageID      sql.NullString `json:"summary_message_id"`
	Cost                  float64        `json:"cost"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalPromptTokens,
		arg.TotalCompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.ProjectID,
		&i.RootSessionID,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.UserSetTitle,
	)
	return i, err
}
